### ISSUE TITLE
 TemplateRuntimeError issue after log4j-core and log4j-api update.

### ISSUE THREAD

**Issue by papiveron** [claranet/ansible-role-log4shell#7]
Hi,

I ran the log4j scanner successfully (without any runtime issue) before update my apache tomcat webapp code.

After that I did the following to update my jar files :

- I stopped tomcat service
- I deleted log4j files: log4j-api-2.14.0.jar and log4j-core-2.14.0.jar from <TOMCAT_INSTALL_DIR>/webapps/licserver/WEB-INF/lib/
- Went o https://logging.apache.org/log4j/2.x/download.html and downloades Apache Log4j 2 binary (zip)
- Extracted log4j-api-2.17.0.jar and log4j-core-2.17.0.jar from the downloaded zip and copy it to <TOMCAT_INSTALL_DIR>/webapps/licserver/WEB-INF/lib/
- Started the tomcat service.
- And then reran the scanner as follow and got the below error :

```
[root@infra-vm centos]# ansible-playbook log4j-scanner.yml
[WARNING]: No inventory was parsed, only implicit localhost is available

[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] *********************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [claranet.log4shell : include_tasks] ********************************************************************************************************************************************************************************************************************
included: /root/.ansible/roles/claranet.log4shell/tasks/install.yml for localhost

TASK [claranet.log4shell : install - Install requirements] ***************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [claranet.log4shell : include_tasks] ********************************************************************************************************************************************************************************************************************
included: /root/.ansible/roles/claranet.log4shell/tasks/search/lsof.yml for localhost

TASK [claranet.log4shell : lsof - Run lsof] ******************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [claranet.log4shell : lsof - Process data from lsof (search 'log4j-core-')] *****************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TemplateRuntimeError: no filter named 'split'
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

[root@infra-vm centos]#
```

Here is the traceback of the failing task:

```

TASK [claranet.log4shell : lsof - Process data from lsof (search 'log4j-core-')] *****************************************************************************************************************************************************************************
task path: /root/.ansible/roles/claranet.log4shell/tasks/search/lsof.yml:6
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 145, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 592, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/task.py", line 268, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python2.7/site-packages/ansible/playbook/base.py", line 435, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 584, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 539, in template
    disable_lookups=disable_lookups,
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 804, in do_template
    res = j2_concat(rf)
  File "<template>", line 17, in root
  File "/usr/lib64/python2.7/site-packages/jinja2/filters.py", line 1016, in do_list
    return list(value)
  File "/usr/lib64/python2.7/site-packages/jinja2/filters.py", line 1117, in do_map
    for item in seq:
  File "/usr/lib64/python2.7/site-packages/jinja2/filters.py", line 1118, in do_map
    yield func(item)
  File "/usr/lib64/python2.7/site-packages/jinja2/filters.py", line 1285, in func
    name, item, args, kwargs, context=context
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 493, in call_filter
    fail_for_missing_callable("no filter named %r", name)
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 120, in fail_for_missing_callable
    raise TemplateRuntimeError(msg)
TemplateRuntimeError: no filter named 'split'

fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
Do you think it's an ansible related issue? May be a problem with the ansible version? I check the role code at line 6 and it really has a `map('split'...)` statement.

Ansible version :

```
[centos@infra-vm ~]$ ansible --version
ansible 2.8.7
  config file = None
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
[centos@infra-vm ~]$
```
Best regards,
Eugène NG

**Comment by ElieDeloumeau** [comment]
Hi Eugène,

This role needs at least Ansible 4 (2.11).
And FYI, Python 2 is no longer supported 😅 

Regards,
Élie
